services:
  # mysql:
  #   image: mysql:8
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=openpasswd
  #     - MYSQL_USER=open
  #     - MYSQL_PASSWORD=passwd
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=openpasswd
      - POSTGRES_USER=open
      - POSTGRES_PASSWORD=passwd
      
      