services:
  openpasswd:
    build: .
    ports:
      - 7777:7777
    environment:
      - DATABASE_URL=postgres://open:passwd@postgres:5432/openpasswd
      - RUST_LOG=info
      - JWT_SECRET=openpasswd
      - DATABASE_POOL_SIZE=15
      - CORS_ALLOW_ORIGIN=*
      - REDIS_URL=redis://redis:6379/
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=openpasswd
      - POSTGRES_USER=open
      - POSTGRES_PASSWORD=passwd
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
      
      