services:
  # mysql:
  #   image: mysql:8
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=openpass
  #     - MYSQL_USER=open
  #     - MYSQL_PASSWORD=vault
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=openpass
      - POSTGRES_USER=open
      - POSTGRES_PASSWORD=vault
      
      